# Generated by Django 4.2.26 on 2025-11-29 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_store',
            field=models.BooleanField(default=True, help_text='Automatically store memories'),
        ),
        migrations.AddField(
            model_name='user',
            name='retention_period',
            field=models.CharField(default='indefinite-84', help_text='Memory retention period: 7-days, 30-days, 90-days, indefinite-84, indefinite-forever', max_length=50),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('memory_created', 'Memory Created'), ('conversation_created', 'Conversation Created'), ('message_sent', 'Message Sent'), ('team_member_added', 'Team Member Added'), ('model_used', 'Model Used')], max_length=30)),
                ('description', models.TextField(help_text='Human-readable description of the activity')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional activity metadata')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.workspace')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['workspace', '-timestamp'], name='api_activit_workspa_71d5f0_idx')],
            },
        ),
    ]
